# Deploy desarrollado por Gamatecnologias.com <soporte@gamatecnologias.com>
name: Publicar en Producción
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Compilacion-Publicacion-FrontEnd:
    name: Publicar en Producción
    runs-on: ubuntu-18.04 #ubuntu-latest
    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Subir archivos por FTP al servidor
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_URL }} # URL del servidor donde se publicara el nuevo modulo
          username: ${{ secrets.FTP_USER }} # Usuario del FTP del servidor
          password: ${{ secrets.FTP_PASSWORD }} # Contraseña del FTP del servidor
          server-dir: ${{ secrets.FTP_DIR }} # Direcctorio de instalacion de WHMCS
